# Generated by Django 6.0.7 on 2026-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='content6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='content7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='content8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='content9',
            field=models.TextField(blank=True, default=''),
        ),
    ]
